### PR TITLE
Support existing saved json

### PR DESCRIPTION
**Pull request by ellesde**
Fixes an issue with importing existing saved json

### CODE REVIEW

**Comment by ellesde** [comment]
@Zarroc2762 Tested with my existing saved json. It works for the most part but ATK is very slightly off. I see like 1-2 stat point difference between in game and the optimizer.

**Comment by Zarroc2762** [comment]
@ellesde Tested it too. Seems like it's working so far. The stat difference probably comes from some kind of rounding issue between ingame and the optimizer.

**Comment by Maytland** [comment]
Hello dude, I have so trouble at the moment to use the gear importer. I usually use the online version "https://colab.research.google.com/drive/1BGnBnthe8ETnih1SU1PBC4UBjSjinusK#scrollTo=WU2qjaRb6yMu" but i think it is broken so I wanna use the offline version, but it didn't work too so I come to you to know how can i import my gears.

**Comment by ellesde** [comment]
> Hello dude, I have so trouble at the moment to use the gear importer. I usually use the online version "https://colab.research.google.com/drive/1BGnBnthe8ETnih1SU1PBC4UBjSjinusK#scrollTo=WU2qjaRb6yMu" but i think it is broken so I wanna use the offline version, but it didn't work too so I come to you to know how can i import my gears.

Hey! Yeah sure I could try and help out. Would suggest you create a new issue tho and describe what you're trying to do and what's not working. Also upload any json you might be using so I could test with it.

**Comment by Maytland** [comment]
When I finish with the online version, I have a Json with a lot of stats but when I put it in the optimizer I have this message. 

E7 Error screen 1

For the Json with the offline version, I have a Json with no item but I can put the json in the optimizer without alert message. So I don't know.

**Comment by ellesde** [comment]
Mind sharing that json? I need it so I can see what's wrong with it.

**Comment by Maytland** [comment]
[json online.txt](https://github.com/Zarroc2762/E7-Gear-Optimizer/files/4398100/json.online.txt)

**Comment by Maytland** [comment]
[Json offline.txt](https://github.com/Zarroc2762/E7-Gear-Optimizer/files/4398105/Json.offline.txt)

**Comment by ellesde** [comment]
@Maytland Sorry doesn't look like I can help you.

This is what the file you sent me looks like:
code

The reason why its not working for you is because the contents of the file looks messed up. The optimizer breaks when its trying to import `"mainStat": ["", 6000]`. There is no stat specified like `atk`, `hp`, `def`, etc so it doesn't know what to do. You might not have imported correctly or the gear importer is broken.

The reason why the offline json file doesn't give an error is because there's nothing to import.

The only way you can use the optimizer is if you get a hold of a correctly exported json file or manually enter the gear yourself into the optimizer. Sorry I couldn't be of more help.

**Comment by Zarroc2762** [comment]
@Maytland Seems like some people messed with the code of the original importer file instead of making a copy. I made a copy of an earlier version [here](https://colab.research.google.com/drive/1adonQ_oMWd56ftdDZQjnKB8n1K1ESaon). This version should still work.

**Pull request merged**
